connection:
  info:
    ip: 127.0.0.1
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: examples/datasets/mnist.npz
  name: MnistTFDataHandler
  path: ibmfl.util.data_handlers.mnist_keras_data_handler
fusion:
  name: TierIterAvgFusionHandler
  path: ibmfl.aggregator.fusion.tier_iter_avg_fusion_handler
hyperparams:
  global:
    max_timeout: 60
    num_parties: 4
    rounds: 3
    termination_accuracy: 0.9
    tiers: 2
  local:
    training:
      epochs: 3
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
